name: Linux

on:
  push:
    branches: [ main ]

jobs:
  build_and_run:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo chmod +x "${GITHUB_WORKSPACE}/Scripts/ubuntu_install.sh"
          sudo "${GITHUB_WORKSPACE}/Scripts/ubuntu_install.sh"
          
      - name: Build Project | All
        run: |
          bazel build //... -c dbg
          bazel build //... -c opt